### PR TITLE
onParserGetVariableValueSwitch: Improve selectRowCount by using wiki_dbname

### PR DESCRIPTION
**Pull request by paladox**
Instead of doing * we look at wiki_dbname. We don't need to be looking at all the other fields to do a row count.

### CODE REVIEW

**Comment by BlankEclair** [comment]
The underlying code does not appear to use `$var` for much?

https://github.com/wikimedia/mediawiki/blob/0ab2ee7aecbafb43e399937810b3733b691f488c/includes/libs/rdbms/database/Database.php#L1381-L1417

**Comment by paladox** [comment]
@BlankEclair it uses it on line 1385

**Comment by BlankEclair** [comment]
`$column` is only used to construct `$column IS NOT NULL` ([which is not necessary for wiki_dbname](https://github.com/miraheze/CreateWiki/blob/4dfc655e4975bef60975632736015294073f2718/sql/cw_wikis.sql#L2)) and when using DISTINCT (which we don't use)

**Comment by BlankEclair** [comment]
Plus, `SQLPlatform#extractSingleFieldFromList()` is basically just a nop for us:

https://github.com/wikimedia/mediawiki/blob/0ab2ee7aecbafb43e399937810b3733b691f488c/includes/libs/rdbms/platform/SQLPlatform.php#L1948-L1966

**Pull request closed without merging**
