### PR TITLE
Add (any) option to sort options dropdowns and default to it (T6577)

### PR DESCRIPTION
**Pull request by Universal-Omega**

### CODE REVIEW

**Comment by dmehus** [comment]
@Universal-Omega What do commits https://github.com/miraheze/WikiDiscover/pull/36/commits/954cdc042e668343fc6b234ad36c646476fb2447 and https://github.com/miraheze/WikiDiscover/pull/36/commits/fb6f685442c1636458cbe7e76b310d719e44fada do? Maybe this was sort of what I was asking about on the Phabricator ticket, but didn't ask all that clearly. :D

**Comment by Universal-Omega** [comment]
> @Universal-Omega What do commits [954cdc0](https://github.com/miraheze/WikiDiscover/commit/954cdc042e668343fc6b234ad36c646476fb2447) and [fb6f685](https://github.com/miraheze/WikiDiscover/commit/fb6f685442c1636458cbe7e76b310d719e44fada) do? Maybe this was sort of what I was asking about on the Phabricator ticket, but didn't ask all that clearly. :D

It is, I understood what you asked after another task was opened so I am doing it now, and the linked ticket is to your task.

**Comment by dmehus** [comment]
> > @Universal-Omega What do commits [954cdc0](https://github.com/miraheze/WikiDiscover/commit/954cdc042e668343fc6b234ad36c646476fb2447) and [fb6f685](https://github.com/miraheze/WikiDiscover/commit/fb6f685442c1636458cbe7e76b310d719e44fada) do? Maybe this was sort of what I was asking about on the Phabricator ticket, but didn't ask all that clearly. :D
> 
> It is, I understood what you asked after another task was opened so I am doing it now, and the linked ticket is to your task.

Oh, okay, cool. Thanks! :)

**Comment by Universal-Omega** [comment]
> > > @Universal-Omega What do commits [954cdc0](https://github.com/miraheze/WikiDiscover/commit/954cdc042e668343fc6b234ad36c646476fb2447) and [fb6f685](https://github.com/miraheze/WikiDiscover/commit/fb6f685442c1636458cbe7e76b310d719e44fada) do? Maybe this was sort of what I was asking about on the Phabricator ticket, but didn't ask all that clearly. :D
> > 
> > 
> > It is, I understood what you asked after another task was opened so I am doing it now, and the linked ticket is to your task.
> 
> Oh, okay, cool. Thanks! :)

No problem!

**Pull request merged**
